import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/molecules/Header";
import Footer from "@/components/molecules/footer";
import Spinner from "@/components/atoms/Spinner";
import { AuthProvider } from "@/utils/AuthContext";
import LanguageSelector from "@/components/molecules/LanguageSelector";

import {NextIntlClientProvider} from 'next-intl';
import {getLocale} from 'next-intl/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  font-sans h-full bg-slate-100 `}
      >
        <AuthProvider>
          <NextIntlClientProvider>
            <header className="h-[7vh]">
              <Header />
            </header>
            <main className="h-[93vh] mt-11">
              {children}
              <Footer/>
            </main>
            <div className="fixed bottom-4 right-4">
              <LanguageSelector />
            </div>
          </NextIntlClientProvider>
          <Spinner />
        </AuthProvider>
      </body>
    </html>
  );
}